services:
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    ports:
      - 8080:80
    volumes:
      - pgadmin_config:/pgadmin4/servers.json
  postgres_users:
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${USERS_DB_PASSWORD}
      - POSTGRES_USER=${USERS_DB_USERNAME}
      - POSTGRES_DB=${USERS_DB_DATABASE}
    volumes:
      - db_users:/var/lib/postgresql/data
    ports:
      - ${USERS_DB_PORT}:5432
  mongodb_catalog:
    image: mongo:6.0.2
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${CATALOG_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${CATALOG_DB_PASSWORD}
    volumes:
      - db_catalog:/data/db
    ports:
      - ${CATALOG_DB_PORT}:27017
  mongodb_cart:
    image: mongo:6.0.2
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${CART_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${CART_DB_PASSWORD}
    volumes:
      - db_cart:/data/db
    ports:
      - ${CART_DB_PORT}:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8090:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${CART_DB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${CART_DB_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${CART_DB_USERNAME}:${CART_DB_PASSWORD}@mongodb_cart:27017/
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
volumes:
  pgadmin_config:
  db_users:
  db_cart:
  db_catalog:
