services:
  db_users:
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${USERS_DB_PASSWORD}
      - POSTGRES_USER=${USERS_DB_USERNAME}
      - POSTGRES_DB=${USERS_DB_DATABASE}
    volumes:
      - db_users:/var/lib/postgresql/data
    ports:
      - ${USERS_DB_PORT}:5432
  db_catalog:
    image: mongo:6.0.2
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${CATALOG_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${CATALOG_DB_PASSWORD}
    volumes:
      - db_catalog:/data/db
    ports:
      - ${CATALOG_DB_PORT}:27017

  backend_cart:
    image: cart:latest
    restart: on-failure
    depends_on:
      - db_mongo
    env_file:
      - ./cart/docker.env
    build:
      context: ./cart
      dockerfile: Dockerfile.backend
    ports:
      - 8013:8000
  rabbitmq_cart:
    image: rabbitmq_cart:latest
    restart: on-failure
    depends_on:
      - rabbitmq
      - db_mongo
    env_file:
      - ./cart/docker.env
    build:
      context: ./cart
      dockerfile: Dockerfile.rabbitmq

  backend_orders:
    image: orders:latest
    restart: on-failure
    depends_on:
      - db_mongo
    env_file:
      - ./orders/docker.env
    build:
      context: ./orders
      dockerfile: Dockerfile.backend
    ports:
      - 8014:8000
  rabbitmq_orders:
    image: rabbitmq_orders:latest
    restart: on-failure
    depends_on:
      - rabbitmq
      - db_mongo
    env_file:
      - ./orders/docker.env
    build:
      context: ./orders
      dockerfile: Dockerfile.rabbitmq

  db_mongo:
    image: mongo:6.0.2
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${CART_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${CART_DB_PASSWORD}
    volumes:
      - db_mongo:/data/db
    ports:
      - ${CART_DB_PORT}:27017
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    ports:
      - 8070:80
    volumes:
      - pgadmin_config:/pgadmin4/servers.json
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8090:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${CART_DB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${CART_DB_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${CART_DB_USERNAME}:${CART_DB_PASSWORD}@db_mongo:27017/
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
volumes:
  pgadmin_config:
  db_users:
  db_mongo:
  db_catalog:
