services:
  gateway:
    ports:
      - 9000:8000

  backend_users:
    ports:
      - 9001:8000

  backend_catalog:
    ports:
      - 9002:8000

  backend_cart:
    ports:
      - 9003:8000

  backend_orders:
    ports:
      - 9004:8000

  backend_order_history:
    ports:
      - 9005:8000

  db_postgres:
    ports:
      - 5432:5432

  db_mongo:
    ports:
      - 27017:27017

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    ports:
      - 8070:80
    volumes:
      - pgadmin_config:/pgadmin4/servers.json

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8090:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${CART_DB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${CART_DB_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${CART_DB_USERNAME}:${CART_DB_PASSWORD}@db_mongo:27017/
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true

  rabbitmq:
    ports:
      - 15672:15672
      - 5672:5672
volumes:
  pgadmin_config:
