services:
  postgres:
    image: mongo:6.0.2
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${CATALOG_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${CATALOG_DB_PASSWORD}
    volumes:
      - db_catalog:/data/db
    ports:
      - ${CATALOG_DB_PORT}:27017

volumes:
  db_catalog:
