services:
  postgres:
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${USERS_DB_PASSWORD}
      - POSTGRES_USER=${USERS_DB_USERNAME}
      - POSTGRES_DB=${USERS_DB_DATABASE}
    volumes:
      - db_users:/var/lib/postgresql/data
    ports:
      - ${USERS_DB_PORT}:5432

volumes:
  db_users:
