services:
  postgres:
    image: postgres:14.5-alpine
    container_name: postgres-users
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - db_users:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432

volumes:
  db_users:
